// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using estoque.Data;

#nullable disable

namespace estoque.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    [Migration("20231003212223_PrimeiroContatoComBanco")]
    partial class PrimeiroContatoComBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("estoque.Models.CategoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descrição")
                        .HasColumnType("longtext");

                    b.Property<int?>("FornecedorModelId")
                        .HasColumnType("int");

                    b.Property<int?>("FuncionarioModelId")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorModelId");

                    b.HasIndex("FuncionarioModelId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("estoque.Models.EstoqueModel", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("NívelEstoqueMáximo")
                        .HasColumnType("double");

                    b.Property<double>("NívelEstoqueMínimo")
                        .HasColumnType("double");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("IdProduto");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("estoque.Models.FornecedorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereço")
                        .HasColumnType("longtext");

                    b.Property<int?>("FuncionarioModelId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioModelId");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("estoque.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .HasColumnType("longtext");

                    b.Property<bool>("Logado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("estoque.Models.ProdutoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrição")
                        .HasColumnType("longtext");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<int?>("FuncionarioModelId")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdFornecedor")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("Preço")
                        .HasColumnType("double");

                    b.Property<double?>("QuantidadeEstoque")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("FuncionarioModelId");

                    b.HasIndex("IdCategoria")
                        .IsUnique();

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("estoque.Models.CategoriaModel", b =>
                {
                    b.HasOne("estoque.Models.FornecedorModel", null)
                        .WithMany("ListaDeCategorias")
                        .HasForeignKey("FornecedorModelId");

                    b.HasOne("estoque.Models.FuncionarioModel", null)
                        .WithMany("Categorias")
                        .HasForeignKey("FuncionarioModelId");
                });

            modelBuilder.Entity("estoque.Models.EstoqueModel", b =>
                {
                    b.HasOne("estoque.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("estoque.Models.FornecedorModel", b =>
                {
                    b.HasOne("estoque.Models.FuncionarioModel", null)
                        .WithMany("Fornecedores")
                        .HasForeignKey("FuncionarioModelId");
                });

            modelBuilder.Entity("estoque.Models.ProdutoModel", b =>
                {
                    b.HasOne("estoque.Models.FornecedorModel", "Fornecedor")
                        .WithMany("ListaDeProdutos")
                        .HasForeignKey("FornecedorId");

                    b.HasOne("estoque.Models.FuncionarioModel", null)
                        .WithMany("Produtos")
                        .HasForeignKey("FuncionarioModelId");

                    b.HasOne("estoque.Models.CategoriaModel", "Categoria")
                        .WithOne("Produto")
                        .HasForeignKey("estoque.Models.ProdutoModel", "IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("estoque.Models.CategoriaModel", b =>
                {
                    b.Navigation("Produto");
                });

            modelBuilder.Entity("estoque.Models.FornecedorModel", b =>
                {
                    b.Navigation("ListaDeCategorias");

                    b.Navigation("ListaDeProdutos");
                });

            modelBuilder.Entity("estoque.Models.FuncionarioModel", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Fornecedores");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
