// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using estoque.Data;

#nullable disable

namespace EstoqueApi.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    [Migration("20231123141844_CriandoTabelaEstoque")]
    partial class CriandoTabelaEstoque
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("estoque.Models.CategoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("estoque.Models.FornecedorCategoria", b =>
                {
                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("FornecedorId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("FornecedorCategorias");
                });

            modelBuilder.Entity("estoque.Models.ProdutoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdFornecedor")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Preco")
                        .HasColumnType("double");

                    b.Property<double>("QuantidadeEstoque")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdFornecedor", "IdCategoria");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("FornecedorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("estoque.Models.FornecedorCategoria", b =>
                {
                    b.HasOne("estoque.Models.CategoriaModel", "Categoria")
                        .WithMany("FornecedorCategoria")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FornecedorModel", "Fornecedor")
                        .WithMany("FornecedorCategoria")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("estoque.Models.ProdutoModel", b =>
                {
                    b.HasOne("estoque.Models.CategoriaModel", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria");

                    b.HasOne("FornecedorModel", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("IdFornecedor");

                    b.HasOne("estoque.Models.FornecedorCategoria", "FornecedorCategoria")
                        .WithMany()
                        .HasForeignKey("IdFornecedor", "IdCategoria");

                    b.Navigation("Categoria");

                    b.Navigation("Fornecedor");

                    b.Navigation("FornecedorCategoria");
                });

            modelBuilder.Entity("estoque.Models.CategoriaModel", b =>
                {
                    b.Navigation("FornecedorCategoria");
                });

            modelBuilder.Entity("FornecedorModel", b =>
                {
                    b.Navigation("FornecedorCategoria");
                });
#pragma warning restore 612, 618
        }
    }
}
