### Cadastrar categoria
POST https://localhost:7295/api/categorias
Content-Type: application/json

{
    "nome": "Categoria Teste",
    "descricao": "Descrição da Categoria Teste",
}

### Visualizar categoria por ID
GET https://localhost:7295/api/categorias/1


### Listar todas as categorias
GET https://localhost:7295/api/categorias



### Atualizar categoria
PUT https://localhost:7295/api/categorias/1
Content-Type: application/json

{
    "nome": "Nova Categoria",
    "descricao": "Nova Descrição",
    "idProduto": 2
}



### Remover categoria por ID
DELETE https://localhost:7295/api/categorias/1

